config/routes.rb
Rails.application.routes.draw do
  root controller: :athletes, action: :index

authenticate :user do
  resources :athletes, shallow: true
  put 'toggle/:id', to: 'athletes#toggle', as: :toggle_voting
  put 'publish', to: 'athletes#publish', as: :publish
  put 'revert', to: 'athletes#revert', as: :revert_results
  post 'push', to: 'athletes#custom_push_notification', as: :push_notification
end
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :athletes, except: [:new]
      resources :results, only: [:index]
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  validates :name, :age, :home, presence: true
  has_one_attached :image

  def open_or_close_voting
    self.votingOpen == false ? self.votingOpen = true : self.votingOpen = false
    self.save
  end

  def self.all_has_raced
    all.each do |athlete|
      athlete.hasraced = true
      athlete.save
    end
  end

  def self.all_has_not_raced
    all.each do |athlete|
      athlete.hasraced = false
      athlete.save
    end
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :athlete, dependent: :destroy

  def updated_votes(params)
    self.rating_collection << params[:vote].to_i
    self.score = (self.rating_collection.sum) / (self.rating_collection.length)
    self.score.round(2)
    self.number_of_votes = self.rating_collection.length
    self.save
  end

  def self.publish_results
    all.each do |result|
      result.has_raced = true
      result.save
    end
  end

  def self.revert_results
    all.each do |result|
      result.has_raced = false
      result.save
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include DeviseTokenAuth::Concerns::User
end

app/controllers/api/v1/athletes_controller.rb
class Api::V1::AthletesController < ApiController

  before_action :find_athlete_and_result
  before_action :authenticate_api_v1_user!, only: [:create, :destroy, :edit]

  def index
    sorted_athletes
    render json: @sorted_athletes, status: :ok
  end

  def show
    render json: @athlete, serializer: Athlete::ShowSerializer, status: :ok
  end

  def update
    render_message('Thank you for casting your vote!') if @result.updated_votes(params)
  end

  def edit
    render_message('Athlete updated successfully!')  if @athlete.update(athlete_params)
  end

  def create
    athlete = Athlete.new(athlete_params)
    if athlete.save
      Result.create(athlete: athlete)
      render_message('Athlete successfully created!')
    else
      render_message('Please fill in all fields.')
    end
  end

  def destroy
    athlete = Athlete.find_by(id: params[:id])
    athlete.destroy
    render_message('Athlete successfully deleted!')
  end

  private

  def athlete_params
    params.permit(:name, :age, :home)
  end

  def sorted_athletes
    athletes = Athlete.all
    @sorted_athletes = athletes.sort_by { |athlete| athlete[:starttime] }
    @sorted_athletes
  end

  def find_athlete_and_result
    @athlete = Athlete.find_by(id: params[:id])
    @result = Result.find_by(athlete: params[:id])
  end

  def render_message(message)
    render json: { status: message }
  end
end

app/controllers/api/v1/results_controller.rb
class Api::V1::ResultsController < ApiController

  def index
    render json: sorted_results, status: :ok
  end

  private
  def sorted_results
    results = Result.all
    sorted_results = results.sort_by { |result| result[:score] }.reverse
    sorted_results.each { |result| result.valid_score = true if result.number_of_votes > 4 }
    sorted_results
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  include DeviseTokenAuth::Concerns::SetUserByToken
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
    layout "application"
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
include NotificationsHandler
  def index
    if current_user
      sorted_results
      sorted_athletes
    else
      redirect_to new_user_session_path
    end
  end

  def create
    athlete = Athlete.new(athlete_params)
    if athlete.save
      Result.create(athlete: athlete)
      flash[:success] = 'Athlete successfully created'
       redirect_to root_path
    else
      flash[:error] = athlete.errors.full_messages.first
      redirect_back(fallback_location: root_path)
    end
  end

  def show
    @athlete = Athlete.find_by(id: params[:id])
  end

  def edit
    @athlete = Athlete.find_by(id: params[:id])
  end

  def destroy
    athlete = Result.find_by(athlete_id: params[:id])
    athlete.destroy
    redirect_to root_path
  end

  def update
    athlete = Athlete.find_by(id: params[:id])
    if athlete.update(athlete_params)
     flash.now[:success] = 'Athlete successfully edited'
     redirect_to athlete_path(athlete)
    else
     flash[:error] = error_message(athlete)
     redirect_to edit_athlete_path(athlete)
    end
  end

  def toggle
    athlete = Athlete.find_by(id: params[:id])
    athlete.open_or_close_voting
    push_notification(params) if athlete.votingOpen == true
    redirect_to root_path
  end

  def publish
    if Result.publish_results
      Athlete.all_has_raced
      flash[:success] = 'Result successfully published'
      push_notification(params)
      redirect_to root_path
    else
      flash[:error] = 'You have no results to publish'
      redirect_to root_path
    end
  end

  def revert
    if Result.revert_results
      Athlete.all_has_not_raced
      flash[:success] = 'Result successfully reverted'
      redirect_to root_path
    else
      flash[:error] = 'You have no results to revert'
      redirect_to root_path
    end
  end

  def custom_push_notification
    flash[:success] = 'Push notification successfully sent' if push_notification(params)
    redirect_to root_path
  end


  private

  def sorted_results
    results = Result.all
    @sorted_results = results.sort_by { |result| result[:score] }.reverse
    @sorted_results.each { |result| result.valid_score = true if result.number_of_votes > 4 }
    @sorted_results
  end

  def sorted_athletes
    athletes = Athlete.all
    @sorted_athletes = athletes.sort_by { |athlete| athlete[:starttime] }
    @sorted_athletes
  end

  def athlete_params
    params.require(:athlete).permit(:name, :age, :home, :image, :starttime)
  end
end

app/controllers/concerns/notifications_handler.rb
require 'net/http'
module NotificationsHandler
  extend ActiveSupport::Concern

  def file_data(name)
    File.read(Rails.root.to_s + "/app/controllers/concerns/files/#{name}.txt")
  end

  def push_notification(params)
    if params[:action] == 'custom_push_notification'
      params = eval(file_data('custom_message'))
    elsif params[:action] == 'toggle'
      obj = Athlete.find_by(id: params[:id])
      params = eval(file_data('voting_params'))
    else
      params = eval(file_data('results_params'))
    end

    headers = eval(file_data('notifications_headers'))
    one_signal_url = 'https://onesignal.com/api/v1/notifications'

    uri = URI.parse(one_signal_url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.path, headers)
    request.body = params.to_json
    http.request(request)
  end
end

app/views/athletes/edit.html.erb
<div class="form">
<h1>Edit Athlete</h1>

<%= form_with model: @athlete, local: true do |form| %>
  <p>
    <%= form.label :name %>
    <br>
    <%= form.text_field :name, value: @athlete.name %>
  </p>
  <p>
    <%= form.label :home %>
    <br>
    <%= form.text_field :home, value: @athlete.home %>
  </p>
  <p>
    <%= form.label :age %>
    <br>
    <%= form.text_field :age %>
  </p>
  <p>
    <%= form.label :starttime %>
    <br>
    <%= form.text_field :starttime%>
  </p>
    <% if @athlete.image.attachment %>
      <%= image_tag @athlete.image, width: '250' %>
    <% end %>
    <%= form.file_field :image %>
    <%= form.submit value: 'Update Athlete' %>
  <% end %>
</div>

app/views/athletes/index.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>


<div class="container">
  <div class="controllers">
    <%= form_with url: publish_path, method: :put, local: true do |form| %>
    <%= form.submit value: 'Publish Result', class:"btn btn-info ctrl" %>
  <% end %>
  <%= form_with url: revert_results_path, method: :put, local: true do |form| %>
  <%= form.submit value: 'Revert Result', class:"btn btn-info ctrl" %>
<% end %>
<%= link_to 'New Athlete', new_athlete_path, class:"btn btn-info ctrl" %>
</div>

<h1>Custom Push Notitification</h1>

<%= form_with url: push_notification_path, class:'form-group', method: :post, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, class:'form-control', style: 'width: 300px' %>
  <%= form.label :content %>
  <%= form.text_field :content, class:'form-control', style: 'width: 300px'  %>
  <%= form.submit value: 'Send Notification', class: 'btn btn-info mt-3' %>
<% end %>

<h1 class="section">Athletes</h1>

<% if @sorted_athletes %>
<ul class="list-group athlete">
  <% @sorted_athletes.each do |athlete| %>
    <div>
      <li class="list-group-item m-2">
        <h5><%= athlete.name %></h5>
        <div>Voting open:
          <strong><%= athlete.votingOpen %></strong>
        </div>

        <%= form_with url: toggle_voting_path(athlete), method: :put, local: true do |form| %>
        <%= form.submit value: 'Open/Close Voting', id: 'voting', class: 'btn btn-info' %>
      <% end %>

      <%= link_to 'Edit Athlete', edit_athlete_path(athlete), class: "btn btn-secondary" %>

      <%= form_with url: athlete_path(athlete), method: :delete, local: true do |form| %>
      <%= form.submit value: 'Delete', class: "btn btn-secondary" %>
    <% end %>
  </li>
</div>
<% end %>
</ul>
<% end %>

<h1 class="section">Results</h1>
<br/>
<% if @sorted_results %>
<% position = 1 %>
<ul class="list-group results">
<% @sorted_results.each do |result| %>
  <% if result.valid_score == true %>
    <div>
      <li class="list-group-item m-2" style="width: 325px">
        <h5>
          No.
          <%= position %>
          <%= result.athlete.name %>
        </h5>
        <div>Score:
          <strong><%= result.score %></strong>
        </div>
        <div>Number of votes:
          <strong><%= result.number_of_votes %></strong>
        </div>
      </li>
    </div>
    <% position += 1 %>
    <% end %>
  <% end %>
</ul>
<% end %>
<h1 class="section">Insufficient votes</h1>

<% if @sorted_results %>
<ul class="list-group insufficient-votes">
  <% @sorted_results.each do |result| %>
    <% if result.valid_score == false %>
      <div>
        <li class="list-group-item m-2" style="width: 325px">
          <h5>
            <%= result.athlete.name %>
          </h5>
          <div>Score:
            <strong><%= result.score %></strong>
          </div>
          <div>Number of votes:
            <strong><%= result.number_of_votes %></strong>
          </div>
        </li>
      </div>
    <% end %>
  <% end %>
</ul>
<% end %>

app/views/athletes/new.html.erb
<div class="form">
<%= form_with model: Athlete.new, local: true do |form| %>
  <p>
  <%= form.label :name %>
  <br>
  <%= form.text_field :name %>
  </p>
  <p>
  <%= form.label :home %>
  <br>
  <%= form.text_field :home %>
  </p>
  <p>
  <%= form.label :age %>
  <br>
  <%= form.text_field :age %>
  </p>
  <p>
  <%= form.label :starttime %>
  <br>
  <%= form.text_field :starttime%>
  </p>
  <p><%= form.file_field :image %></p>
  <%= form.submit %>
<% end %>
</div>

app/views/athletes/show.html.erb
<h1> <%= @athlete.name %> </h1>

<% if @athlete.image.attachment %>
  <%= image_tag @athlete.image, width: '250' %>
<% end %>
<p> Home Range: <%= @athlete.home %> </p>
<p> Age: <%= @athlete.age %> </p>
<p> Race Time: <%= @athlete.starttime %> </p>

<%= link_to 'Edit', edit_athlete_path(@athlete) %>
<%= link_to 'Delete Athlete', athlete_path(@athlete), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <ul class="nav">
      <% if current_user %>
      <li class="nav-item">
        <a class="nav-link" href="#athletes_section">Athletes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#results">Results</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#insufficient_votes">Insufficient Votes</a>
      </li>
        <li class="nav-item"> <%= form_with url: destroy_user_session_path, method: :delete, local: true do |form| %> </li>
          <li class="nav-link"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% end %>
      <% end %>
    </ul>

      <% flash.each do |key, value| %>
        <div class="text-center">
          <%= value  %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>